- hosts: peer_cloudlab, client_cloudlab
  remote_user: amwotil
  become: false

  tasks:
  - name: Get Noler PIDs
    shell: ps -ef | grep -v grep | grep -w noler | awk '{print $2}' | awk 'FNR == 1 {print}'
    ignore_errors: yes
    register: noler_pids

  - name: Kill running processes
    shell: "kill {{ item }}"
    with_items:
    - "{{ noler_pids.stdout_lines }}"

  - name: Show PIDs
    debug:
      var: noler_pids