---
- hosts: peer_cloudlab, client_cloudlab
  remote_user: amwotil
  become: false

  pre_tasks:
  - name: update repositories
    apt: update_cache=yes
    become: true
    changed_when: false

  tasks:
  - name: check if cargo is installed
    shell: command -v cargo
    register: cargo_exists
    ignore_errors: yes

  - name: Download Installer
    when: cargo_exists is failed
    get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'
    tags:
      - rust

  - name: install rust/cargo
    when: cargo_exists is failed
    shell: /tmp/sh.rustup.rs -y
    tags:
      - rust

  - name: Clone the LowPaxos github repository
    git:
      repo: https://github.com/crane-cloud/lowpaxos
      dest: ~/lowpaxos
      version: performance
      clone: yes
      update: yes

- hosts: peer_cloudlab
  remote_user: amwotil
  become: false
  tasks:

  - name: set the id of the peer
    set_fact:
      id: "{{ ansible_enp1s0d1.ipv4.address.split('.')[3] }}"

  # - name: Start a noler peer
  #   command: ~/.cargo/bin/cargo run --bin noler -- -c config.txt -i {{ id }}
  #   args:
  #     chdir:  ~/lowpaxos/noler
  #   ignore_errors: yes


# - hosts: client_cloudlab
#   tasks:
#   - name: Start a noler client
#     command: ~/.cargo/bin/cargo run --bin noler-client -- -c config.txt -f log.txt -n 100
#     args:
#       chdir:  ~lowpaxos/noler