[package]
name = "kvstore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stateright = "0.30"
serde = { version = "1.0", features = ["derive"] }

#noler = { path = "../noler" }